### ISSUE TITLE
[Vimeo Player] [Youtube Player] (full-width)

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#12]
Like the image block, but plays a Vimeo video.

**Comment by bronsonmolen** [comment]
Paul's notes:
[Vimeo Player] [Youtube Player] (full-width)
This should be good. Minor tweaks only. YT and Vimeo have their own blocks. Should only need the video ID

**Comment by bronsonmolen** [comment]
<img width="359" alt="Screenshot 2023-01-24 at 9 38 49 AM" src="https://user-images.githubusercontent.com/118481216/214353299-ef901875-008e-4c0f-9486-5d10d3ae4be6.png">

**Comment by solomon71** [comment]
Refactor to new design (2/2/2023) -

**Comment by solomon71** [comment]
@snowiewdev - can we use #28 issue and close this one?

**Comment by snowiewdev** [comment]
@solomon71 Sure!
