### ISSUE TITLE
new [Services]

### ISSUE THREAD

**Issue by bronsonmolen** [solomon71/tbx-olympus#15]

**Comment by bronsonmolen** [comment]
<img width="359" alt="Screenshot 2023-01-24 at 9 41 34 AM" src="https://user-images.githubusercontent.com/118481216/214354221-ed6c0177-4be5-463d-8f07-b83d21417979.png">

**Comment by bronsonmolen** [comment]
This is new. Needs a new Google doc entry and block code. 

Should create a common button to use too.

**Comment by bronsonmolen** [comment]
This is no longer present in the latest designs

**Comment by solomon71** [comment]
![Image](https://user-images.githubusercontent.com/7327/216683597-03312782-726f-4682-9fb4-afc62e4e7702.png)

new block design Feb. 2023 designs

**Comment by solomon71** [comment]
Trying to get clarification on the Learn More CTA. Comment is open on Figma file

**Comment by solomon71** [comment]
In google doc, have the CTA link as optional and show CTA if there is not a null/undefined/"" value.

**Comment by solomon71** [comment]
From design -- "This section should have each title clickable and when selected, change the copy on the right side to correspond. Titles should probably have a hover to show they are clickable, maybe just a 30% increase in darkness or something like that"
