### ISSUE TITLE
new [Partners]

### ISSUE THREAD

**Issue by bronsonmolen** [solomon71/tbx-olympus#16]
Paul's notes:
This is new. Needs a new Google doc entry and block code.

**Comment by bronsonmolen** [comment]
<img width="348" alt="Screenshot 2023-01-24 at 9 44 08 AM" src="https://user-images.githubusercontent.com/118481216/214354589-6d33fae2-988d-48db-8ed7-00eb17726a38.png">

**Comment by bronsonmolen** [comment]
Partners is a suggestion. We can change the name.

**Comment by bronsonmolen** [comment]
Update:
![Image](https://user-images.githubusercontent.com/118481216/214909572-e4259c05-ae51-4e19-aa86-676186e5f5eb.png)

https://www.figma.com/file/toPXlIHGxdI2lUbKaMI6tz/Thinkingbox-Enterprise-ideas?node-id=1887%3A4896&t=uiZOapKfJXWNnv8z-1

**Comment by solomon71** [comment]
Link out to a relevant work page if available, if not an option, link out to the brand landing page.
