### ISSUE TITLE
new [Checklist]

### ISSUE THREAD

**Issue by bronsonmolen** [solomon71/tbx-olympus#17]
Paul's notes:
This is new. Needs a new Google doc entry and block code. This looks to need to be designed out as this is a screengrab of another site’s block.
<img width="357" alt="Screenshot 2023-01-24 at 9 46 06 AM" src="https://user-images.githubusercontent.com/118481216/214355004-6623dd66-59e8-4a17-9134-a9d804f7fa8a.png">

**Comment by solomon71** [comment]
stale, no longer in design
