### ISSUE TITLE
[Columns]

### ISSUE THREAD

**Issue by bronsonmolen** [solomon71/tbx-olympus#19]
Paul's notes:
This should be good. Minor tweaks only.

**Comment by bronsonmolen** [comment]
<img width="351" alt="Screenshot 2023-01-24 at 9 49 39 AM" src="https://user-images.githubusercontent.com/118481216/214355833-a717cb5b-3f7b-4cfb-8b4c-c01e7960cf6d.png">

**Comment by solomon71** [comment]
<img width="897" alt="Screenshot 2023-02-03 at 11 44 22 AM" src="https://user-images.githubusercontent.com/7327/216682446-cb2f29d9-d7bb-4ae1-ac9a-f24e87f9cc48.png">

Update to this block with new Feb 2023 design
