### ISSUE TITLE
Work Detail - Services [case-study-services]

### ISSUE THREAD

**Issue by bronsonmolen** [solomon71/tbx-olympus#21]
This is new. Needs a new Google doc entry and block code.
<img width="355" alt="Screenshot 2023-01-24 at 9 52 36 AM" src="https://user-images.githubusercontent.com/118481216/214356512-76d427c8-5a0c-4e2c-ac29-068a20cc8ea2.png">

**Comment by bronsonmolen** [comment]
Services Performed does not need to be the name.

**Comment by bronsonmolen** [comment]
Another example (needs options for color variation):
![Image](https://user-images.githubusercontent.com/118481216/214910794-5755c64a-b36b-4f01-9b56-1ed16cf07e45.png)

Figma: https://www.figma.com/file/toPXlIHGxdI2lUbKaMI6tz/Thinkingbox-Enterprise-ideas?node-id=1887%3A5431&t=uiZOapKfJXWNnv8z-1

**Comment by solomon71** [comment]
addressed in https://github.com/solomon71/tbx-olympus/pull/27
