### ISSUE TITLE
new [Tall Image]

### ISSUE THREAD

**Issue by bronsonmolen** [solomon71/tbx-olympus#22]
Paul's notes:
This is new. Needs a new Google doc entry and block code.
<img width="349" alt="Screenshot 2023-01-24 at 9 53 44 AM" src="https://user-images.githubusercontent.com/118481216/214356769-660bf7cd-5ec4-46d9-91ae-d18628050c6a.png">

**Comment by bronsonmolen** [comment]
https://www.figma.com/file/toPXlIHGxdI2lUbKaMI6tz/Thinkingbox-Enterprise-ideas?node-id=1791%3A4678&t=WUnkCx0x8JIGtj8v-1

**Comment by bronsonmolen** [comment]
https://www.figma.com/file/toPXlIHGxdI2lUbKaMI6tz/Thinkingbox-Enterprise-ideas?node-id=1791%3A4678&t=WUnkCx0x8JIGtj8v-1

**Comment by bronsonmolen** [comment]
Could be the same as #23 and #24

**Comment by bronsonmolen** [comment]
Latest designs (should be final): 
![Image](https://user-images.githubusercontent.com/118481216/214911378-4c621f49-977c-4f83-81d4-bda7f16b03ec.png)
![Image](https://user-images.githubusercontent.com/118481216/214911379-21028678-11f7-4fdd-91ba-ef2eb13c730b.png)

The intention here is to allow these to be gifs.

> Can we also make an option for the image to be on the right or the left?
Update: We do not need the image to be on the right. Just the left side is fine.

Figma: https://www.figma.com/file/toPXlIHGxdI2lUbKaMI6tz/Thinkingbox-Enterprise-ideas?node-id=1887%3A4896&t=uiZOapKfJXWNnv8z-1

**Comment by solomon71** [comment]
verified, merged to dev
