### ISSUE TITLE
Bug: [Nav] Mobile nav responsiveness issue.

### ISSUE THREAD

**Issue by christian-boswell** [solomon71/tbx-olympus#25]
If nav left open on mobile, it remains 100vh if browser adjusted to desktop. 

<img width="1496" alt="Screenshot 2023-01-25 at 10 53 14 AM" src="https://user-images.githubusercontent.com/81317058/214643622-5ff3873d-a122-4edc-aa7d-b6c5bd76b0a5.png">

**Comment by bronsonmolen** [comment]
This is a subtask of #3

**Comment by snowiewdev** [comment]
Other notes for fixing the responsive ui bugs:

- if started at desktop & shrinking to mobile, the duplicated text effects are not hided 
![Home-TBX-Enterprise](https://user-images.githubusercontent.com/72127025/217937006-76f96f50-07e8-4f54-bdaf-3dd4ce433390.png)
