### ISSUE TITLE
[Nav]

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#3]

**Comment by solomon71** [comment]
<img width="1101" alt="Screenshot 2022-11-30 at 2 45 18 PM" src="https://user-images.githubusercontent.com/7327/204914776-c7ec2877-2294-4cd7-9e6c-37b0cecde8c7.png">
<img width="1178" alt="Screenshot 2022-11-30 at 2 45 04 PM" src="https://user-images.githubusercontent.com/7327/204914779-f2da9f77-2a35-48cb-a1bd-f76265c0853f.png">

The nav needs styling work.

- The logo is pixelated, please use SVG for this.
- Match the fonts and weight. (let me know if you need any fonts)
- Uppercase the links
- Overall sizing needs to match the Figma file. 
- Present a rollover idea for the nav, instead of the stock underline

**Comment by bronsonmolen** [comment]
Paul's notes:
Needs work, may need a whole rewrite.

This has been created. It lives as its own file. `nav`
It gets pulled in on every page.
