### ISSUE TITLE
[Section Lead]

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#30]
New block, see screenshot from figma

![Image](https://user-images.githubusercontent.com/7327/216685592-6173024d-a82b-4ef3-9bcd-694ff557275b.png)

**Comment by solomon71** [comment]
Can this work with this block? LMK

<img width="972" alt="Screenshot 2023-02-03 at 1 33 55 PM" src="https://user-images.githubusercontent.com/7327/216705717-d08e32d7-d61f-40b3-b14c-9d8a91858fec.png">

**Comment by saugatmalla** [comment]
These can probably be handled with the `section-metadata` block.

Eg;
| section metadata | |
|---|---|
|style    |  grid-half , justify-between |   

the style classes must be defined with proper value.

**Comment by snowiewdev** [comment]
Created block with section lead. Just in case if the section needs to add in javascript in future.
