### ISSUE TITLE
[Header Statement]

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#32]
New block, see screenshot from figma

![Image](https://user-images.githubusercontent.com/7327/216703552-ea0164d3-d4dd-4574-961d-d33274023493.png)

**Comment by saugatmalla** [comment]
This can probably be handled with the `section-metadata` block.

Eg;
| section metadata | |
|---|---|
|style    |  grid-half |   

the style classes must be defined with proper value.
