### ISSUE TITLE
[Work Brand Tile]

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#33]
New block, see screenshot from figma

![Image](https://user-images.githubusercontent.com/7327/216710306-0c553419-f856-4818-9d73-88e7861d975e.png)

** The idea is to have these as images or video (w/ supplied poster frame that author puts into table cell). For 2/3/2023, let's just support image stills for now. We will refactor if we get to video support.

**Comment by snowiewdev** [comment]
Added todo in codebase to note for supporting video in future
