### ISSUE TITLE
[vimeo-player] [youtube-player] [mobile] - not rendering

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#43]
On iOS Chrome & Safari video blocks not rendering.

**Comment by solomon71** [comment]
See attached render from iPhone 14 Pro

![Image](https://user-images.githubusercontent.com/7327/218827561-6320fe2b-8ce4-46b6-830b-25be7e9d9570.PNG)

**Comment by snowiewdev** [comment]
It's rendering on chrome on my mobile device, but it takes some time. Or should I just create a placeholder cover image so that it doesn't appear empty while loading?
