### ISSUE TITLE
[Image CaseStudy Card] -> handle a video link or create new block

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#52]
looking for a new block that will support looping mp4 files. See https://enterprise.thinkingbox.com/services/ page. The static images will become a looping mp4. Staying away from animated gifs if possible. I've attached a sample mp4 to use.

https://user-images.githubusercontent.com/7327/222509923-63dc0cce-99c1-402d-a2b0-add5a3dc7d5c.mp4

**Comment by solomon71** [comment]
I removed the audio track to test smoother looping
https://user-images.githubusercontent.com/7327/222557765-3767466f-7598-47b7-bdd1-1c6ca5d72638.mp4

**Comment by solomon71** [comment]
Can you test this like we have the services pages setup? @saugatmalla

**Comment by solomon71** [comment]
<img width="1433" alt="Screenshot 2023-03-02 at 3 21 13 PM" src="https://user-images.githubusercontent.com/7327/222572640-fb464479-dc3a-407d-86bf-1f232b4e19af.png">

in a layout like the services page has

**Comment by saugatmalla** [comment]
> Can you test this like we have the services pages setup? @saugatmalla

Here: https://video--tbx-olympus--solomon71.hlx.page/drafts/saugat/tbx-services
