### ISSUE TITLE
[Testimonial]

### ISSUE THREAD

**Issue by solomon71** [solomon71/tbx-olympus#7]
Part of #5 
See approach page from figma

**Comment by bronsonmolen** [comment]
![Image](https://user-images.githubusercontent.com/118481216/214909092-a50dbb9e-dced-4ff3-8f69-d30056255e20.png)

https://www.figma.com/file/toPXlIHGxdI2lUbKaMI6tz/Thinkingbox-Enterprise-ideas?node-id=1887%3A5114&t=uiZOapKfJXWNnv8z-1

**Comment by solomon71** [comment]
addressed in https://github.com/solomon71/tbx-olympus/pull/26
